export const ADD_CURRENT_ID = 'ADD_CURRENT_ID';











export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_STATE = 'GET_STATE';
export const GET_REALTIME_TEMP_HUMIDITY = 'GET_REALTIME_TEMP_HUMIDITY';
export const GET_TEMP_EACH_DAY = 'GET_TEMP_EACH_DAY';
export const GET_HUMIDITY_EACH_DAY = 'GET_HUMIDITY_EACH_DAY';
export const GET_TEMP_BY_TIME = 'GET_TEMP_EACH_MONTH';
export const GET_HUMIDITY_BY_TIME = 'GET_HUMIDITY_EACH_MONTH';
export const GET_BUMP_WORKING = 'GET_BUMP_WORKING';
export const GET_REALTIME_BUMP_STATUS = 'GET_REALTIME_BUMP_STATUS';
export const GET_DETAIL_REALTIME_SENSOR = 'GET_DETAIL_REALTIME_SENSOR';
export const TOGGLE_STATUS_SEND = 'TOGGLE_STATUS_SEND';
export const POST_NAME_BUMP = 'POST_NAME_BUMP';
export const POST_SETTING_BUMP = 'POST_SETTING_BUMP';
export const GET_ERROR_CODE = 'GET_ERROR_CODE';
export const POST_ERROR_CODE = 'POST_ERROR_CODE';
export const GET_LIST_DOING_TASK = 'GET_LIST_DOING_TASK';
export const DELETE_CALENDER_LIST = 'DELETE_CALENDER_LIST';
export const GET_TOKEN = 'GET_TOKEN';